version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./webapp:/opt/webapp
  db:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
  redis:
    image: redis:3.2.8
    ports:
      - "6379:6379"