version: '2'
services:
  thing-api:
    build: thing-api
    container_name: thing-api
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./webapp:/opt/webapp
  thing-ui:
    build: thing-ui
    container_name: thing-ui
    ports:
      - "5001:5001"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./webapp:/opt/webapp
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
  redis:
    image: redis:3.2.8
    ports:
      - "6379:6379"
